-- Generate Fonts for the addon

if CLIENT then

-- CRAFTING TABLE FONTS

	surface.CreateFont( "CT_SplashFontBtn", {
		font = "Calibri",
		extended = false,
		size = 64,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "CT_SplashFontLarge", {
		font = "Calibri",
		extended = false,
		size = 72,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "CT_SplashFontRegular", {
		font = "Calibri",
		extended = false,
		size = 68,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "CT_SplashFontSmall", {
		font = "Calibri",
		extended = false,
		size = 48,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )

	surface.CreateFont( "CT_StatFont", {
		font = "Calibri",
		extended = false,
		size = 28,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

	surface.CreateFont( "CT_PanelHuge", {
		font = "Calibri",
		extended = false,
		size = 44,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
	surface.CreateFont( "CT_PanelLarge", {
		font = "Calibri",
		extended = false,
		size = 36,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
	surface.CreateFont( "CT_PanelRegular", {
		font = "Calibri",
		extended = false,
		size = 28,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "CT_PanelMedium", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "CT_PanelSmall", {
		font = "Calibri",
		extended = false,
		size = 20,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

-- ENTITY FONTS
	surface.CreateFont( "TreeFont", {
		font = "Arial",
		extended = false,
		size = 22,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )

	surface.CreateFont( "DropFont", {
		font = "Arial",
		extended = false,
		size = 28,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
	surface.CreateFont( "CraftingTableFont", {
		font = "Calibri Lt",
		extended = false,
		size = 48,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
	surface.CreateFont( "CrateFrontReg", {
		font = "Arial",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = true ,
	} )	
	
	surface.CreateFont( "CrateFrontSmall", {
		font = "Arial",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
-- INVENTORY FONTS

	surface.CreateFont( "CRFT_InvFontSmall", {
		font = "Calibri",
		extended = false,
		size = 16,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

	surface.CreateFont( "CRFT_InvFontReg", {
		font = "Calibri",
		extended = false,
		size = 18,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

	surface.CreateFont( "CRFT_InvFontLarge", {
		font = "Calibri",
		extended = false,
		size = 20,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = true ,
	} )

-- GUI FONTS
		surface.CreateFont( "CRFT_StatFont", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )
		
		surface.CreateFont( "CRFT_RankFont", {
		font = "Calibri",
		extended = false,
		size = 28,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

		surface.CreateFont( "CRFT_LevelFont", {
		font = "Calibri",
		extended = false,
		size = 18,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
		surface.CreateFont( "CRFT_GainFont", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
	
		surface.CreateFont( "CRFT_GainFontLarge", {
		font = "Calibri",
		extended = false,
		size = 48,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )

		surface.CreateFont( "CRFT_XPFont", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )
end