if SERVER then return end

-- UI FONTS

	surface.CreateFont( "FALCH_hoveringText", {
		font = "Calibri",
		extended = false,
		size = 48,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_xpLabel", {
		font = "Calibri",
		extended = false,
		size = 30,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_lvLabel", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_discountLabel", {
		font = "Calibri",
		extended = false,
		size = 20,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_Tooltip", {
		font = "Calibri",
		extended = false,
		size = 24,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_TooltipCost", {
		font = "Calibri",
		extended = false,
		size = 18,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "FALCH_FamName", {
		font = "Calibri",
		extended = false,
		size = 32,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_FamDesc", {
		font = "Calibri",
		extended = false,
		size = 20,
		weight = 500,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )
	
	surface.CreateFont( "FALCH_FamCost", {
		font = "Calibri",
		extended = false,
		size = 22,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = false,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = false,
		additive = false,
		outline = false ,
	} )		
	
	surface.CreateFont( "FALCH_Stacks", {
		font = "Calibri",
		extended = false,
		size = 42,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = true,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )	
	
	surface.CreateFont( "FALCH_StacksMsg", {
		font = "Calibri",
		extended = false,
		size = 22,
		weight = 600,
		blursize = 0,
		scanlines = 0,
		antialias = true,
		underline = false,
		italic = true,
		strikeout = false,
		symbol = false,
		rotary = false,
		shadow = true,
		additive = false,
		outline = false ,
	} )		
	